Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -34,12 +34,16 @@ jobs:
       run: |
         kubesec scan ./my-chart/*.yaml > kubesec_output.json && cat kubesec_output.json
 
-    - name: Check validation result
+    - name: Run kubesec scan and check validation result
       run: |
-       if grep -q '"score":.*[[:space:]]-?[1-9]' kubesec_output.json; then
-       echo "Some issues found in Kubernetes manifests. Fail the workflow."
-        exit 1
-       else
-        echo "All Kubernetes manifests passed validation."
-         fi
+       kubesec scan ./my-chart/*.yaml > kubesec_output.json
+       if [ $? -ne 0 ]; then
+         echo "Some issues found in Kubernetes manifests. Fail the workflow."
+         cat kubesec_output.json
+          exit 2
+        else
+         echo "All Kubernetes manifests passed validation."
+       fi
+       shell: /usr/bin/bash -e {0}
+
 
