Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -36,9 +36,10 @@ jobs:
 
     - name: Check validation result
       run: |
-        if jq -e '.[] | select(.score < 0)' kubesec_output.json > /dev/null; then
-          echo "Some issues found in Kubernetes manifests. Fail the workflow."
-          exit 1
-        else
-          echo "All Kubernetes manifests passed validation."
-        fi
+       if grep -q '"score":.*[[:space:]]-?[1-9]' kubesec_output.json; then
+       echo "Some issues found in Kubernetes manifests. Fail the workflow."
+        exit 1
+       else
+        echo "All Kubernetes manifests passed validation."
+         fi
+
