Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -25,22 +25,21 @@ jobs:
         curl -sSL https://github.com/controlplaneio/kubesec/releases/download/v2.11.2/kubesec_linux_amd64.tar.gz | tar xz -C /tmp
         sudo mv /tmp/kubesec /usr/local/bin
 
-    # Step 3: Scan Kubernetes manifests with Kubesec
-    - name: Scan Kubernetes manifests
+    - name: Scan and Parse Kubesec Score
       run: |
-        score=$(kubesec scan ./my-charts/*.yaml | jq '.[0].score')
-        echo "Kubesec score: $score"
-        echo "KUBESCORE=$score" >> $GITHUB_ENV
-        if [ "$score" -lt 5 ]; then
-          echo "Security scan did not pass."
-          exit 1
-        fi
-
-    # Step 4: Deploy if Kubesec score is 5 or higher
-    - name: Deploy
-      if: ${{ env.KUBESCORE >= 5 }}
-      run: |
-       echo "Deploying since Kubesec score is $KUBESCORE"
-    # Add your deployment commands here
-
+       output=$(kubesec scan ./my-charts/*.yaml)
+       echo "$output"
+       score=$(echo "$output" | jq '.[0].score' 2>/dev/null)
+    
+       if [ -z "$score" ] || [ "$score" == "null" ]; then
+       echo "Failed to parse score or Kubesec output is not JSON"
+       exit 1
+       fi
+    
+       echo "Kubesec score: $score"
+       echo "KUBESCORE=$score" >> $GITHUB_ENV
+       if [ "$score" -lt 0 ]; then
+       echo "Security scan did not pass."
+       exit 1
+       fi
 
