Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -33,30 +33,20 @@ jobs:
       id: kubesec
       run: |
         kubesec scan ./my-chart/*.yaml > kubesec_output.json 
-        result=$(grep '"score"' kubesec_output.json | cut -d ':' -f2 | sed 's/,//g')
-        integer_result=$((result)) 
-        if [ "$integer_result" -gt 0 ]; then
-        echo "All Kubernetes manifests passed validation."
-        elif [ "$integer_result" -lt 0 ]; then
-        echo "Some issues found in Kubernetes manifests. Fail the workflow."
-        exit 1
-        fi
+        cat kubesec_output.json
 
-
-       #cat kubesec_output.json
-
-   # - name: Check validation result
-      #run: |
-     #  result=$(grep '"score"' kubesec_output.json | cut -d ':' -f2 | sed 's/,//g')
+    - name: Check validation result
+      run: |
+       result=$(grep '"score"' kubesec_output.json | cut -d ':' -f2 | sed 's/,//g')
 
        # Converting the result to an integer
-      # integer_result=$((result)) 
-       #if [ "$integer_result" -gt 0 ]; then
-       #echo "All Kubernetes manifests passed validation."
-       #elif [ "$integer_result" -lt 0 ]; then
-        #echo "Some issues found in Kubernetes manifests. Fail the workflow."
-        #exit 1
-        #fi
+       integer_result=$((result)) 
+        if [ "$integer_result" -gt 0 ]; then
+         echo "All Kubernetes manifests passed validation."
+       elif [ "$integer_result" -lt 0 ]; then
+         echo "Some issues found in Kubernetes manifests. Fail the workflow."
+        exit 1
+        fi
 
         
 
